const commonTechCategories = {
    'Web Platform': [
        { name: 'PHP', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg' },
        { name: 'JavaScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
        { name: 'PostgreSQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
        { name: 'Swift', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg' },
        { name: 'TypeScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
        { name: 'Python', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
        { name: 'Java', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
        { name: 'Ruby', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg' },
        { name: 'C++', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg' },
        { name: 'React JS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
        { name: 'Laravel', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-plain.svg' },
        { name: 'Node.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
    ],
    'Databases': [
        { name: 'MySQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
        { name: 'MongoDB', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
        { name: 'PostgreSQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
        { name: 'Redis', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg' },
        { name: 'SQLite', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg' },
        { name: 'Firebase', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg' },
    ],
    'Cloud & DevOps': [
        { name: 'AWS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg' },
        { name: 'Docker', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
        { name: 'Kubernetes', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg' },
        { name: 'Git', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
        { name: 'Linux', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg' },
        { name: 'Nginx', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nginx/nginx-original.svg' },
    ],
    'Mobile Apps': [
        { name: 'Flutter', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg' },
        { name: 'React Native', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
        { name: 'Swift', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg' },
        { name: 'Kotlin', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg' },
        { name: 'Android', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg' },
        { name: 'iOS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apple/apple-original.svg' },
    ],
    'Other Frameworks': [
        { name: 'Vue.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg' },
        { name: 'Angular', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg' },
        { name: 'Next.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg' },
        { name: 'Django', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg' },
        { name: 'Spring', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg' },
        { name: 'TailwindCSS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg' },
    ],
};

const commonApproachSteps = [
    { title: 'Discovery Phase', desc: 'Understanding your requirements and defining the project scope and objectives.' },
    { title: 'Design and Development', desc: 'Creating the solution with best practices and modern methodologies.' },
    { title: 'Maintenance', desc: 'Ongoing support and improvements to keep your solution performing optimally.' },
    { title: 'Deployment', desc: 'Smooth deployment with minimal disruption to your business operations.' },
    { title: 'Testing and QA', desc: 'Thorough testing to ensure quality and reliability of the delivered solution.' },
];

export const servicesData = {
    'web-development': {
        title: 'Web Development',
        image: 'https://media.istockphoto.com/id/1503858430/vector/website-software-development-concept-web-design-site-and-mobile-app-on-laptop-testing-on.jpg?s=612x612&w=0&k=20&c=k8ckKsgOrPPxohAA_ywg2VXZzdCPptEbOlleRV8Kb7c=',
        description: 'Transform your online presence with our professional web development services. We build responsive, scalable, and user-friendly websites using modern technologies like React, Next.js, Angular, and Vue.js. Our full-stack developers create robust backend systems with Node.js, Python, PHP, and Laravel.',
        description2: 'From simple landing pages to complex enterprise web applications, we deliver solutions that are fast, secure, and optimized for search engines. Our development process follows industry best practices to ensure maintainable and scalable code.',
        keyFeatures: [
            'Responsive web design and development',
            'Progressive Web Applications (PWA)',
            'E-commerce website development',
            'Content Management Systems (CMS)',
            'API development and integration',
            'Website maintenance and support',
            'Performance optimization and SEO',
            'Cross-browser compatibility testing',
        ],
        approachSteps: [
            { title: 'Discovery Phase', desc: 'Data-driven diagnostic and predictive app for improving outcomes. Data-driven solutions tailored to your business needs.' },
            { title: 'Design and Development', desc: 'We create wireframes and high-fidelity designs, then develop the frontend and backend systems.' },
            { title: 'Maintenance', desc: 'Ongoing support, bug fixes, and performance improvements to keep your web application running smoothly.' },
            { title: 'Deployment', desc: 'Secure deployment to cloud platforms with CI/CD pipelines and zero-downtime releases.' },
            { title: 'Testing and QA', desc: 'Comprehensive testing including unit tests, integration tests, and user acceptance testing.' },
        ],
        techCategories: commonTechCategories,
    },

    'app-development': {
        title: 'App Development',
        image: 'https://ncube.com/wp-content/uploads/2022/08/Custom-Software-Application-Development.jpg',
        description: 'We build high-performance mobile applications for iOS and Android platforms using Flutter, React Native, Swift, and Kotlin. Our apps are designed for scalability, performance, and exceptional user experience.',
        description2: 'From consumer apps to enterprise solutions, we deliver mobile applications that engage users and drive business growth. Our development process ensures your app is ready for the App Store and Google Play.',
        keyFeatures: [
            'Native iOS and Android development',
            'Cross-platform development with Flutter & React Native',
            'Push notifications and real-time features',
            'Offline-first architecture',
            'App Store and Play Store submission',
            'In-app purchases and subscriptions',
            'Analytics and crash reporting',
            'App performance optimization',
        ],
        approachSteps: [
            { title: 'Discovery Phase', desc: 'Understanding your target users, business goals, and technical requirements for the mobile app.' },
            { title: 'Design and Development', desc: 'Creating intuitive UI/UX designs and developing native or cross-platform mobile applications.' },
            { title: 'Maintenance', desc: 'Regular updates, bug fixes, and new feature development to keep your app competitive.' },
            { title: 'Deployment', desc: 'Submitting your app to App Store and Google Play with full compliance to store guidelines.' },
            { title: 'Testing and QA', desc: 'Device testing across multiple platforms, OS versions, and screen sizes.' },
        ],
        techCategories: {
            'Mobile Apps': commonTechCategories['Mobile Apps'],
            'Web Platform': [
                { name: 'JavaScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
                { name: 'TypeScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
                { name: 'Node.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
            ],
            'Cloud & DevOps': [
                { name: 'AWS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg' },
                { name: 'Docker', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
                { name: 'Git', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
            ],
            'Databases': [
                { name: 'Firebase', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg' },
                { name: 'MongoDB', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
                { name: 'SQLite', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg' },
            ],
            'Other Frameworks': [
                { name: 'Redux', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg' },
                { name: 'GraphQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg' },
            ],
        },
    },

    'custom-software-development': {
        title: 'Custom Software Development',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnchDsc4T_inxvznqYgd2_HV1L_3qfH3z_ww&s',
        description: 'Our Custom Software Development services deliver cutting-edge solutions tailored to your business needs. We combine industry expertise with the latest technologies to build enterprise-grade applications.',
        description2: 'With a proven track record and experienced team, we ensure your project is delivered on time, within budget, and to the highest quality standards.',
        keyFeatures: [
            'Custom enterprise software solutions',
            'Legacy system modernization',
            'ERP and CRM development',
            'Third-party integrations',
            'Workflow automation',
            'Scalable architecture design',
            'Cloud-native development',
            'Microservices architecture',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'ux-ui-design': {
        title: 'UX/UI Design',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCR2VtMXJJDGdwE-WNkSYNqyByqo3ICu42xw&s',
        description: 'Our UX/UI Design services create stunning, intuitive interfaces that users love. We combine user research, design thinking, and visual creativity to deliver exceptional digital experiences.',
        description2: 'From wireframes to high-fidelity prototypes, our designers craft experiences that are both beautiful and functional, ensuring your product stands out in the market.',
        keyFeatures: [
            'User research and persona creation',
            'Wireframing and prototyping',
            'Visual design and branding',
            'Design system creation',
            'Usability testing',
            'Interactive prototypes',
            'Mobile-first design',
            'Accessibility compliance',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'quality-assurance': {
        title: 'Quality Assurance',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlj8avKmhfhpvHQCsy3Y3Ce6IRwdUqyPSW6g&s',
        description: 'Our Quality Assurance services ensure your software is bug-free, performant, and reliable. We use a comprehensive testing approach to deliver products that meet the highest quality standards.',
        description2: 'Our QA engineers work closely with your development team to catch issues early, reduce costs, and deliver software that your users can trust.',
        keyFeatures: [
            'Manual and automated testing',
            'Performance and load testing',
            'Security vulnerability testing',
            'API testing',
            'Cross-browser compatibility',
            'Mobile device testing',
            'Regression testing',
            'CI/CD pipeline integration',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'gen-ai': {
        title: 'Gen AI',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYqAKZmufTUmYsrG0JCnRdEWGDqv5YUdcM6w&s',
        description: 'Our Generative AI services help businesses leverage the power of artificial intelligence to automate processes, generate content, and unlock new opportunities for growth.',
        description2: 'From AI chatbots to custom LLM integrations, we build intelligent solutions that transform how your business operates and delivers value to customers.',
        keyFeatures: [
            'AI-powered chatbots and assistants',
            'Natural language processing',
            'Image and video generation',
            'AI model fine-tuning',
            'LLM integration',
            'Predictive analytics',
            'Computer vision solutions',
            'AI automation workflows',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'data-analytics': {
        title: 'Data Analytics',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzJwllMIALciB8qE_9Vmsg7j2rEL369y0O1w&s',
        description: 'Our Data Analytics services transform raw data into actionable insights. We build powerful dashboards, reports, and analytics pipelines that help you make smarter business decisions.',
        description2: 'From data warehousing to real-time analytics, our experts design solutions that scale with your business and deliver the insights you need when you need them.',
        keyFeatures: [
            'Business intelligence dashboards',
            'Data visualization',
            'Predictive analytics',
            'Real-time data processing',
            'ETL pipeline development',
            'Data warehousing',
            'Machine learning models',
            'Report automation',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'devops': {
        title: 'DevOps',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIWdJb_AQ9xCdJS6I9VjY3tcr-M5KZG0iW-Q&s',
        description: 'Our DevOps services bridge the gap between development and operations to accelerate delivery, improve reliability, and reduce costs through automation and best practices.',
        description2: 'We help teams adopt DevOps culture and tools, implementing CI/CD pipelines, infrastructure as code, and monitoring solutions that keep your systems running smoothly.',
        keyFeatures: [
            'CI/CD pipeline setup',
            'Infrastructure as code',
            'Container orchestration',
            'Cloud migration',
            'Monitoring and alerting',
            'Security automation',
            'Performance optimization',
            'Disaster recovery planning',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'cloud-maintenance-integration': {
        title: 'Cloud Maintenance & Integration',
        image: 'https://conneximity.com/wp-content/uploads/2025/05/Cloud-Maintenance-Integration.webp',
        description: 'Our Cloud Maintenance & Integration services ensure your cloud infrastructure is always optimized, secure, and cost-effective. We manage and maintain your cloud environment so you can focus on your business.',
        description2: 'From multi-cloud strategies to third-party integrations, our cloud experts handle the complexity so your team can focus on delivering value.',
        keyFeatures: [
            'Cloud infrastructure management',
            'AWS/GCP/Azure integration',
            'Auto-scaling configuration',
            'Cost optimization',
            'Security hardening',
            'Backup and recovery',
            'Performance monitoring',
            'Multi-cloud strategy',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'saas-solutions': {
        title: 'SaaS Solutions',
        image: 'https://cdn.sanity.io/images/91rk3dzx/production/5853dfc6d4a64eac29f7c626d95b9797c8ac01df-1178x613.jpg',
        description: 'Our SaaS Solutions help businesses build and launch scalable software-as-a-service products. We handle everything from architecture design to deployment and ongoing maintenance.',
        description2: 'Whether you\'re building a new SaaS product or modernizing an existing one, our team delivers solutions that are scalable, secure, and ready for growth.',
        keyFeatures: [
            'SaaS product development',
            'Multi-tenant architecture',
            'Subscription management',
            'Usage analytics',
            'API marketplace',
            'White-label solutions',
            'Onboarding automation',
            'Customer portal development',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'e-commerce': {
        title: 'E-commerce',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuo97ekszdsC_ELxFej_JzssUNPqnUek6B0Q&s',
        description: 'Our E-commerce services help businesses build powerful online stores that convert visitors into customers. We create seamless shopping experiences that drive sales and customer loyalty.',
        description2: 'From custom e-commerce platforms to Shopify and WooCommerce development, we deliver solutions that scale with your business and support your growth.',
        keyFeatures: [
            'Custom e-commerce platforms',
            'Shopify and WooCommerce development',
            'Payment gateway integration',
            'Inventory management systems',
            'Order tracking and fulfillment',
            'Mobile commerce apps',
            'SEO optimization',
            'Analytics and reporting',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },

    'staff-augmentation': {
        title: 'Staff Augmentation',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwe-iF4fJLhWAbZ8daRm8X95Go69xMiNB6Tw&s',
        description: 'Our Staff Augmentation services provide you with skilled developers, designers, and tech professionals to extend your team on demand. Scale up or down based on your project needs.',
        description2: 'With access to a global talent pool of vetted professionals, we help you fill skill gaps quickly and cost-effectively without the overhead of full-time hiring.',
        keyFeatures: [
            'Dedicated development teams',
            'On-demand talent scaling',
            'Technical skill gap filling',
            'Project-based hiring',
            'Remote team management',
            'Agile team integration',
            'Knowledge transfer',
            'Cost-effective resourcing',
        ],
        approachSteps: commonApproachSteps,
        techCategories: commonTechCategories,
    },
};